name: Salesforce CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          sfdx --version

      - name: Authenticate Salesforce (PR Validation)
        env:
          SF_AUTH_URL: ${{ secrets.SF_SANDBOX_AUTH_URL }}
        run: |
          echo "$SF_AUTH_URL" > authFile.txt
          sfdx force:auth:sfdxurl:store -f authFile.txt --setalias sandbox --setdefaultusername
          
      - name: Run Validation Deployment
        run: |
          sf project deploy validate --source-dir force-app --target-org sandbox --verbose

  deploy-to-sandbox:
    name: Deploy to sandbox
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli
          sfdx --version

      - name: Authenticate Salesforce
        env:
          SF_AUTH_URL: ${{ secrets.SF_SANDBOX_AUTH_URL }}
        run: |
          echo $SF_AUTH_URL > authFile.txt
          sfdx auth:sfdxurl:store -f authFile.txt --setalias sandbox --setdefaultdevhubusername

      - name: Deploy to sandbox
        run: |
          sfdx force:source:deploy -p force-app --targetusername sandbox --wait 10 --verbose
