name: Salesforce CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    container: salesforce/salesforcedx:latest-full
    
    steps:
      - name: Checkout Repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate Salesforce (PR Validation)
        env:
          SF_AUTH_URL: ${{ secrets.SF_SANDBOX_AUTH_URL }}
        run: |
          echo "$SF_AUTH_URL" > authFile.txt
          sf org login sfdx-url --sfdx-url-file authFile.txt --setalias sandbox --setdefaultusername

      - name: Create Delta Output Directory
        run: mkdir -p delta

      - name: Install sfdx-git-delta Plugin
        run: |
          echo y | sfdx plugins:install sfdx-git-delta
          sfdx plugins --core

      - name: Generate Delta using sfdx-git-delta
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch origin main
          sfdx sgd:source:delta --to HEAD --from origin/main --output delta --generate-delta

      - name: Validate Delta Deployment with Specific Test Class
        run: |
          if [ -d "delta/force-app" ] && [ "$(find delta/force-app -type f | wc -l)" -gt 0 ]; then
            echo "Delta found. Proceeding with validation..."
            sf project deploy start \
              --source-dir delta/force-app \
              --target-org sandbox \
              --dry-run \
              --test-level RunSpecifiedTests \
              --tests "ChangePasswordControllerTest" \
              --verbose
          else
            echo "No deployable metadata found in delta. Skipping validation."
          fi

  deploy-to-sandbox:
    name: Deploy to Sandbox
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    container: jfgarcia268/vlocity_sfdx:latest

    steps:
      - name: Checkout Repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate Salesforce (Deploy)
        env:
          SF_AUTH_URL: ${{ secrets.SF_SANDBOX_AUTH_URL }}
        run: |
          echo "$SF_AUTH_URL" > authFile.txt
          sf org login sfdx-url --sfdx-url-file authFile.txt --alias sandbox --set-default

      - name: Create Delta Output Directory
        run: mkdir -p delta

      - name: Generate Delta using sfdx-git-delta (HEAD~1 to HEAD)
        run: |
          git fetch origin main
          sfdx sgd:source:delta --to HEAD --from HEAD~1 --output delta --generate-delta

      - name: Deploy Delta to Sandbox with Specific Test Class
        run: |
          if [ -d "delta/force-app" ] && [ "$(find delta/force-app -type f | wc -l)" -gt 0 ]; then
            echo "Deployable delta found. Deploying..."
            sf project deploy start \
              --source-dir delta/force-app \
              --target-org sandbox \
              --test-level RunSpecifiedTests \
              --tests "ChangePasswordControllerTest" \
              --verbose
          else
            echo "No deployable metadata found. Skipping deployment."
          fi
