name: Salesforce CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli
          sfdx --version

      - name: Install & Run Salesforce Code analyzer
        run: |
          sf plugins install @salesforce/sfdx-scanner
          mkdir reports
          sf scanner run --format html --target "force-app" --engine "eslint-lwc,retire-js,pmd,cpd" --category "Design, Best Practices,Code Style, Performance, Security" --outfile reports/scan-reports.html
         

      - name: Authenticate Salesforce (PR Validation)
        env:
          SF_AUTH_URL: ${{ secrets.SF_SANDBOX_AUTH_URL }}
        run: |
          echo "$SF_AUTH_URL" > authFile.txt
          sfdx force:auth:sfdxurl:store -f authFile.txt --setalias sandbox --setdefaultusername
          
      - name: Run Validation Deployment
        run: |
          sfdx force:source:deploy -p force-app --targetusername sandbox --checkonly --verbose -l NoTestRun

  deploy-to-sandbox:
    name: Deploy to sandbox
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli
          sfdx --version

      - name: Authenticate Salesforce
        env:
          SF_AUTH_URL: ${{ secrets.SF_SANDBOX_AUTH_URL }}
        run: |
          echo $SF_AUTH_URL > authFile.txt
          sfdx force:auth:sfdxurl:store -f authFile.txt --setalias sandbox --setdefaultusername

      - name: Deploy to sandbox
        run: |
          sfdx force:source:deploy -p force-app --targetusername sandbox --verbose
