name: Salesforce CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI and sfdx-git-delta Plugin
        run: |
          npm install --global @salesforce/cli
          echo y | sf plugins install sfdx-git-delta
          sfdx --version
          sfdx plugins --core

      - name: Authenticate Salesforce (PR Validation)
        env:
          SF_AUTH_URL: ${{ secrets.SF_SANDBOX_AUTH_URL }}
        run: |
          echo "$SF_AUTH_URL" > authFile.txt
          sf org login sfdx-url --sfdx-url-file authFile.txt --setalias sandbox --setdefaultusername

      - n
