name: Salesforce CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout Repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for delta

      - name: Install Salesforce CLI and sfdx-git-delta Plugin
        run: |
          npm install --global @salesforce/cli
          echo y | sf plugins install sfdx-git-delta
          sfdx --version
          sfdx plugins --core

      - name: Authenticate Salesforce
        env:
          SF_AUTH_URL: ${{ secrets.SF_SANDBOX_AUTH_URL }}
        run: |
          echo "$SF_AUTH_URL" > authFile.txt
          sf org login sfdx-url --sfdx-url-file authFile.txt --setalias sandbox --setdefaultusername

      - name: Create Delta Output Directory
        run: mkdir -p delta

      - name: Generate Delta Package
        run: |
          git fetch origin main
          sfdx sgd:source:delta --to HEAD --from origin/main --output delta --generate-delta

      - name: Validate Delta Deployment
        run: |
          if [ -d "delta/force-app" ] && [ "$(find delta/force-app -type f | wc -l)" -gt 0 ]; then
            echo "Delta found. Proceeding with validation..."
            sf project deploy start \
              --source-dir delta/force-app \
              --target-org sandbox \
              --dry-run \
              --test-level RunLocalTests \
              --verbose
          else
            echo "No changes detected in delta. Skipping validation."
          fi
